<?php

namespace App\Repository;

use App\Entity\AlbumType;
use App\Entity\Language;
use App\Entity\Translation;
use App\Entity\TranslationKey;
use Doctrine\ORM\Query\Expr\Join;

/**
 * Class AlbumTypeRepository.
 *
 * @package App\Repository
 * @template-extends AbstractRepository<AlbumType>
 *
 * @author  Codememory
 */
class AlbumTypeRepository extends AbstractRepository
{
    /**
     * @inheritDoc
     */
    protected ?string $entity = AlbumType::class;

    /**
     * @inheritDoc
     */
    protected ?string $alias = 'at';

    /**
     * @param null|Language $language
     *
     * @return array
     */
    public function all(?Language $language): array
    {
        $orderBy = [];
        $qb = $this->getQueryBuilder();

        $qb->leftJoin(Language::class, 'l', Join::WITH, $qb->expr()->eq(
            'l.code',
            ':lang_code'
        ));

        if (false !== $sortByTitle = $this->sortService->get('title')) {
            $qb->leftJoin(TranslationKey::class, 'tk', Join::WITH, $qb->expr()->eq(
                'tk.key',
                'at.titleTranslationKey'
            ));
            $qb->leftJoin(Translation::class, 't', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('t.language', 'l'),
                $qb->expr()->eq('t.translationKey', 'tk')
            ));
            $qb->orderBy('t.translation', $this->getOrderType($sortByTitle));
            $qb->setParameter('lang_code', $language->getCode());
        }

        if (false !== $sortByKey = $this->sortService->get('key')) {
            $orderBy['key'] = $this->getOrderType($sortByKey);
        }

        return parent::findByCriteria([], $orderBy);
    }
    
    protected function findByCriteria(array $criteria, array $orderBy = []): array
    {

        return parent::findByCriteria($criteria, $orderBy); // TODO: Change the autogenerated stub
    }

}
