<?php

namespace App\Enum;

enum WebSocketClientMessageTypeEnum
{
    case CREATE_STREAM_MULTIMEDIA_OFFER_BETWEEN_CURRENT_ACCOUNT;
    case CREATE_STREAM_MULTIMEDIA_OFFER_BETWEEN_FRIEND;
    case MULTIMEDIA_STREAM_OFFER;
    case ACCEPT_OFFERED_STREAMING;
    case REJECT_OFFERED_STREAMING;
    case USER_NOTIFICATION;
}