version: '3'

services:
  # Application php8.0 and symfony
  app:
    container_name: app
    platform: linux/amd64
    build:
      context: ./
      dockerfile: "${DEV_PATH}/php${PHP_VERSION}-fpm/Dockerfile"
      args:
        workdir: ${WORKDIR}
        app_path: ${APP_PATH}
    volumes:
      - "${APP_PATH}:${WORKDIR}"
      - "${DEV_PATH}/php${PHP_VERSION}-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
    links:
      - mysql
      - redis

  # Database MySQL
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_USER_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DBNAME}"
    ports:
      - "3306:3306"
    volumes:
      - "${DATA_PATH}/mysql:/var/lib/mysql"

  # Database No SQL Redis
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    restart: always
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - "${DEV_PATH}/redis/default.conf:/etc/redis/conf.d/redis.conf"

  # Web-Server nginx
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
      - "9000:9000"
      - "443:443"
    volumes:
      - "${DEV_PATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${APP_PATH}:${WORKDIR}"
    links:
      - app