version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_DEV_PATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${API_PATH}:${API_WORKDIR}"
    links:
      - api
      - rabbitmq

  api:
    container_name: api
    build:
      context: ./
      dockerfile: "${DOCKER_DEV_PATH}/php${PHP_VERSION}-fpm/Dockerfile"
      args:
        workdir: ${API_WORKDIR}
        app_path: ${API_PATH}
    expose:
      - "9000"
    volumes:
      - "${API_PATH}:${API_WORKDIR}"
      - "${DOCKER_DEV_PATH}/php${PHP_VERSION}-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
    links:
      - postgres
      - redis
      - s3

  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: unless-stopped
    platform: linux/amd64
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - "${DATA_PATH}/postgres/data:/var/lib/postgresql/data/"

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    restart: always
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - "${DOCKER_DEV_PATH}/redis/default.conf:/etc/redis/conf.d/redis.conf"

  s3:
    container_name: s3
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./data/minio/minio:/data
    environment:
      MINIO_ACCESS_KEY: "${S3_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${S3_SECRET_KEY}"
      MINIO_ROOT_USER: "${S3_USER}"
      MINIO_ROOT_PASSWORD: "${S3_PASSWORD}"
      MINIO_DOMAIN: s3:9000
    command: server /data --console-address ":9001"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBIT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "${RABBIT_VHOST}"
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data/rabbitmq/:/var/lib/rabbitmq/"

  ### WebSocket TODO:

  ### Queue Worker TODO: