framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            amqp_ws:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange:
                  name: ws-users
                  type: direct
                queues:
                  ws-users: ~
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            App\Message\NotificationMessage: async
