controllers:
    resource: ../src/Controller/
    type: annotation

xhprof_bundle:
    resource: ../src/Acme/XhprofBundle/Controller
    type: annotation

api_v1:
    resource: ../src/Controller/Api/V1
    type: annotation
    prefix: /api/v1/{_locale}

web_player:
    resource: ../src/Controller/WebPlayerController.php
    type: annotation
    prefix: /web-player

user_account:
    resource: ../src/Controller/UserAccountController.php
    type: annotation
    prefix: /account

other:
    resource: ../src/Controller/OtherController.php
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
