controllers:
    resource: ../src/Controller/
    type: annotation

api_v1:
    resource: ../src/Controller/Api/V1
    type: annotation
    prefix: /api/v1

kernel:
    resource: ../src/Kernel.php
    type: annotation
