# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    jwt.path.public_key: config/secrets/jwt-public.pem
    jwt.path.private_key: config/secrets/jwt-private.pem

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        autowire: true
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Enums/'
            - '../src/Service/'

    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    # Event Subscribers
    App\EventSubscriber\UserRegistration\SendConfirmationSubscriber:
        tags:
            - {name: kernel.event_subscriber, event: user.registration}

    # Event Listeners

    # Commands
    App\Command\GenerateJwtKeysCommand:
        tags:
            - {name: console.command}
