asset:
  # Resource paths
  paths:
    dist: public/
    assets: resources/front/

  # Active path that will be substituted as a prefix
  activeOutput: dist

  # File aliases
  aliases:
    - "js/app.js@app-js"
    - "css/app.css@app-css"
    - "images/og_cover.png@og_cover"
    - "images/icon_32.png@icon_32"
    - "images/icon_16.png@icon_16"
    - "images/icon.ico@icon"
    - "opensearch.xml@open_search"

  # Webpack builder settings
  webpack:
    # The webpack input files will also be the release files.
    entryFiles:
      js: js/app.js
      sass: scss/app.scss

    # Aliases for modules. Key and value
    moduleAliases: {}

    # Whether comments shall be extracted to a separate file
    extractJsComments: false