<?php

namespace App\DataFixtures;

use App\DataFixtures\Factory\LanguageCodeFactory;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use JetBrains\PhpStorm\Pure;

final class LanguageCodeDataFixture extends AbstractDataFixture implements DependentFixtureInterface
{
    #[Pure]
    public function __construct()
    {
        parent::__construct([
            new LanguageCodeFactory('ab', 'abk', 'languageCode@abkhaz'),
            new LanguageCodeFactory('aa', 'aar', 'languageCode@afar'),
            new LanguageCodeFactory('af', 'afr', 'languageCode@afrikaans'),
            new LanguageCodeFactory('ak', 'aka', 'languageCode@akan'),
            new LanguageCodeFactory('sq', 'alb', 'languageCode@albanian'),
            new LanguageCodeFactory('am', 'amh', 'languageCode@amharic'),
            new LanguageCodeFactory('ar', 'ara', 'languageCode@arabic'),
            new LanguageCodeFactory('an', 'arg', 'languageCode@aragonese'),
            new LanguageCodeFactory('hy', 'hye', 'languageCode@armenian'),
            new LanguageCodeFactory('as', 'asm', 'languageCode@assamese'),
            new LanguageCodeFactory('av', 'ava', 'languageCode@avaric'),
            new LanguageCodeFactory('ae', 'ave', 'languageCode@avestan'),
            new LanguageCodeFactory('ay', 'aym', 'languageCode@aymara'),
            new LanguageCodeFactory('az', 'aze', 'languageCode@azerbaijani'),
            new LanguageCodeFactory('bm', 'bam', 'languageCode@bambara'),
            new LanguageCodeFactory('ba', 'bak', 'languageCode@bashkir'),
            new LanguageCodeFactory('eu', 'eus', 'languageCode@basque'),
            new LanguageCodeFactory('be', 'bel', 'languageCode@belarusian'),
            new LanguageCodeFactory('bn', 'ben', 'languageCode@bengali'),
            new LanguageCodeFactory('bh', 'bih', 'languageCode@bihari'),
            new LanguageCodeFactory('bi', 'bis', 'languageCode@bislama'),
            new LanguageCodeFactory('bs', 'bos', 'languageCode@bosnian'),
            new LanguageCodeFactory('br', 'bre', 'languageCode@breton'),
            new LanguageCodeFactory('bg', 'bul', 'languageCode@bulgarian'),
            new LanguageCodeFactory('my', 'mya', 'languageCode@burmese'),
            new LanguageCodeFactory('ca', 'cat', 'languageCode@catalanValencian'),
            new LanguageCodeFactory('ch', 'cha', 'languageCode@chamorro'),
            new LanguageCodeFactory('ce', 'che', 'languageCode@chechen'),
            new LanguageCodeFactory('ny', 'nya', 'languageCode@chichewaChewaNyanja'),
            new LanguageCodeFactory('zh', 'zho', 'languageCode@chinese'),
            new LanguageCodeFactory('cv', 'chv', 'languageCode@chuvash'),
            new LanguageCodeFactory('kw', 'cor', 'languageCode@cornish'),
            new LanguageCodeFactory('co', 'cos', 'languageCode@corsican'),
            new LanguageCodeFactory('cr', 'cre', 'languageCode@cree'),
            new LanguageCodeFactory('hr', 'hrv', 'languageCode@croatian'),
            new LanguageCodeFactory('cs', 'cze', 'languageCode@czech'),
            new LanguageCodeFactory('da', 'dan', 'languageCode@danish'),
            new LanguageCodeFactory('dv', 'div', 'languageCode@divehiDhivehiMaldivian'),
            new LanguageCodeFactory('nl', 'dut', 'languageCode@dutch'),
            new LanguageCodeFactory('en', 'eng', 'languageCode@english'),
            new LanguageCodeFactory('eo', 'epo', 'languageCode@esperanto'),
            new LanguageCodeFactory('et', 'est', 'languageCode@estonian'),
            new LanguageCodeFactory('ee', 'ewe', 'languageCode@ewe'),
            new LanguageCodeFactory('fo', 'fao', 'languageCode@faroese'),
            new LanguageCodeFactory('fj', 'fij', 'languageCode@fijian'),
            new LanguageCodeFactory('fi', 'fin', 'languageCode@finnish'),
            new LanguageCodeFactory('fr', 'fra', 'languageCode@french'),
            new LanguageCodeFactory('ff', 'ful', 'languageCode@fulaFulahPulaarPular'),
            new LanguageCodeFactory('gl', 'glg', 'languageCode@galician'),
            new LanguageCodeFactory('ka', 'geo', 'languageCode@georgian'),
            new LanguageCodeFactory('de', 'ger', 'languageCode@german'),
            new LanguageCodeFactory('el', 'gre', 'languageCode@greekModern'),
            new LanguageCodeFactory('gn', 'grn', 'languageCode@guaraní'),
            new LanguageCodeFactory('gu', 'guj', 'languageCode@gujarati'),
            new LanguageCodeFactory('ht', 'hat', 'languageCode@haitianHaitianCreole'),
            new LanguageCodeFactory('ha', 'hau', 'languageCode@hausa'),
            new LanguageCodeFactory('he', 'heb', 'languageCode@hebrewModern'),
            new LanguageCodeFactory('hz', 'her', 'languageCode@herero'),
            new LanguageCodeFactory('hi', 'hin', 'languageCode@hindi'),
            new LanguageCodeFactory('ho', 'hmo', 'languageCode@hiriMotu'),
            new LanguageCodeFactory('hu', 'hun', 'languageCode@hungarian'),
            new LanguageCodeFactory('ia', 'ina', 'languageCode@interlingua'),
            new LanguageCodeFactory('id', 'ind', 'languageCode@indonesian'),
            new LanguageCodeFactory('ie', 'ile', 'languageCode@interlingue'),
            new LanguageCodeFactory('ga', 'gle', 'languageCode@irish'),
            new LanguageCodeFactory('ig', 'ibo', 'languageCode@igbo'),
            new LanguageCodeFactory('ik', 'ipk', 'languageCode@inupiaq'),
            new LanguageCodeFactory('io', 'ido', 'languageCode@ido'),
            new LanguageCodeFactory('is', 'ice', 'languageCode@icelandic'),
            new LanguageCodeFactory('it', 'ita', 'languageCode@italian'),
            new LanguageCodeFactory('iu', 'iku', 'languageCode@inuktitut'),
            new LanguageCodeFactory('ja', 'jpn', 'languageCode@japanese'),
            new LanguageCodeFactory('jv', 'jav', 'languageCode@javanese'),
            new LanguageCodeFactory('kl', 'kal', 'languageCode@kalaallisutGreenlandic'),
            new LanguageCodeFactory('kn', 'kan', 'languageCode@kannada'),
            new LanguageCodeFactory('kr', 'kau', 'languageCode@kanuri'),
            new LanguageCodeFactory('ks', 'kas', 'languageCode@kashmiri'),
            new LanguageCodeFactory('kk', 'kaz', 'languageCode@kazakh'),
            new LanguageCodeFactory('km', 'khm', 'languageCode@khmer'),
            new LanguageCodeFactory('ki', 'kik', 'languageCode@kikuyuGikuyu'),
            new LanguageCodeFactory('rw', 'kin', 'languageCode@kinyarwanda'),
            new LanguageCodeFactory('ky', 'kir', 'languageCode@kirghizKyrgyz'),
            new LanguageCodeFactory('kv', 'kom', 'languageCode@komi'),
            new LanguageCodeFactory('kg', 'kon', 'languageCode@kongo'),
            new LanguageCodeFactory('ko', 'kor', 'languageCode@korean'),
            new LanguageCodeFactory('ku', 'kur', 'languageCode@kurdish'),
            new LanguageCodeFactory('kj', 'kua', 'languageCode@kwanyamaKuanyama'),
            new LanguageCodeFactory('la', 'lat', 'languageCode@latin'),
            new LanguageCodeFactory('lb', 'ltz', 'languageCode@luxembourgishLetzeburgesch'),
            new LanguageCodeFactory('lg', 'lug', 'languageCode@luganda'),
            new LanguageCodeFactory('li', 'lim', 'languageCode@limburgishLimburganLimburger'),
            new LanguageCodeFactory('ln', 'lin', 'languageCode@lingala'),
            new LanguageCodeFactory('lo', 'lao', 'languageCode@lao'),
            new LanguageCodeFactory('lt', 'lit', 'languageCode@lithuanian'),
            new LanguageCodeFactory('lu', 'lub', 'languageCode@lubaKatanga'),
            new LanguageCodeFactory('lv', 'lav', 'languageCode@latvian'),
            new LanguageCodeFactory('gv', 'glv', 'languageCode@manx'),
            new LanguageCodeFactory('mk', 'mkd', 'languageCode@macedonian'),
            new LanguageCodeFactory('mg', 'mlg', 'languageCode@malagasy'),
            new LanguageCodeFactory('ms', 'may', 'languageCode@malay'),
            new LanguageCodeFactory('ml', 'mal', 'languageCode@malayalam'),
            new LanguageCodeFactory('mt', 'mlt', 'languageCode@maltese'),
            new LanguageCodeFactory('mi', 'mri', 'languageCode@māori'),
            new LanguageCodeFactory('mr', 'mar', 'languageCode@marathiMarāṭhī'),
            new LanguageCodeFactory('mh', 'mah', 'languageCode@marshallese'),
            new LanguageCodeFactory('mn', 'mon', 'languageCode@mongolian'),
            new LanguageCodeFactory('na', 'nau', 'languageCode@nauru'),
            new LanguageCodeFactory('nv', 'nav', 'languageCode@navajoNavaho'),
            new LanguageCodeFactory('nb', 'nob', 'languageCode@norwegianBokmål'),
            new LanguageCodeFactory('nd', 'nde', 'languageCode@northNdebele'),
            new LanguageCodeFactory('ne', 'nep', 'languageCode@nepali'),
            new LanguageCodeFactory('ng', 'ndo', 'languageCode@ndonga'),
            new LanguageCodeFactory('nn', 'nno', 'languageCode@norwegianNynorsk'),
            new LanguageCodeFactory('no', 'nor', 'languageCode@norwegian'),
            new LanguageCodeFactory('ii', 'iii', 'languageCode@nuosu'),
            new LanguageCodeFactory('nr', 'nbl', 'languageCode@southNdebele'),
            new LanguageCodeFactory('oc', 'oci', 'languageCode@occitan'),
            new LanguageCodeFactory('oj', 'oji', 'languageCode@ojibweOjibwa'),
            new LanguageCodeFactory('cu', 'chu', 'languageCode@churchSlavonic'),
            new LanguageCodeFactory('om', 'orm', 'languageCode@oromo'),
            new LanguageCodeFactory('or', 'ori', 'languageCode@oriya'),
            new LanguageCodeFactory('os', 'oss', 'languageCode@ossetianOssetic'),
            new LanguageCodeFactory('pa', 'pan', 'languageCode@panjabiPunjabi'),
            new LanguageCodeFactory('pi', 'pli', 'languageCode@pāli'),
            new LanguageCodeFactory('fa', 'per', 'languageCode@persian'),
            new LanguageCodeFactory('pl', 'pol', 'languageCode@polish'),
            new LanguageCodeFactory('ps', 'pus', 'languageCode@pashtoPushto'),
            new LanguageCodeFactory('pt', 'por', 'languageCode@portuguese'),
            new LanguageCodeFactory('qu', 'que', 'languageCode@quechua'),
            new LanguageCodeFactory('rm', 'roh', 'languageCode@romansh'),
            new LanguageCodeFactory('rn', 'run', 'languageCode@kirundi'),
            new LanguageCodeFactory('ro', 'ron', 'languageCode@romanianMoldavianMoldovan'),
            new LanguageCodeFactory('ru', 'rus', 'languageCode@russian'),
            new LanguageCodeFactory('sa', 'san', 'languageCode@sanskritSaṁskṛta'),
            new LanguageCodeFactory('sc', 'srd', 'languageCode@sardinian'),
            new LanguageCodeFactory('sd', 'snd', 'languageCode@sindhi'),
            new LanguageCodeFactory('se', 'sme', 'languageCode@northernSami'),
            new LanguageCodeFactory('sm', 'smo', 'languageCode@samoan'),
            new LanguageCodeFactory('sg', 'sag', 'languageCode@sango'),
            new LanguageCodeFactory('sr', 'srp', 'languageCode@serbian'),
            new LanguageCodeFactory('gd', 'gla', 'languageCode@scottishGaelicGaelic'),
            new LanguageCodeFactory('sn', 'sna', 'languageCode@shona'),
            new LanguageCodeFactory('si', 'sin', 'languageCode@sinhalaSinhalese'),
            new LanguageCodeFactory('sk', 'slk', 'languageCode@slovak'),
            new LanguageCodeFactory('sl', 'slv', 'languageCode@slovene'),
            new LanguageCodeFactory('so', 'som', 'languageCode@somali'),
            new LanguageCodeFactory('st', 'sot', 'languageCode@southernSotho'),
            new LanguageCodeFactory('es', 'spa', 'languageCode@spanishCastilian'),
            new LanguageCodeFactory('su', 'sun', 'languageCode@sundanese'),
            new LanguageCodeFactory('sw', 'swa', 'languageCode@swahili'),
            new LanguageCodeFactory('ss', 'ssw', 'languageCode@swati'),
            new LanguageCodeFactory('sv', 'swe', 'languageCode@swedish'),
            new LanguageCodeFactory('ta', 'tam', 'languageCode@tamil'),
            new LanguageCodeFactory('te', 'tel', 'languageCode@telugu'),
            new LanguageCodeFactory('tg', 'tgk', 'languageCode@tajik'),
            new LanguageCodeFactory('th', 'tha', 'languageCode@thai'),
            new LanguageCodeFactory('ti', 'tir', 'languageCode@tigrinya'),
            new LanguageCodeFactory('bo', 'tib', 'languageCode@tibetanStandardTibetanCentral'),
            new LanguageCodeFactory('tk', 'tuk', 'languageCode@turkmen'),
            new LanguageCodeFactory('tl', 'tgl', 'languageCode@tagalog'),
            new LanguageCodeFactory('tn', 'tsn', 'languageCode@tswana'),
            new LanguageCodeFactory('to', 'ton', 'languageCode@tongaTongaIslands'),
            new LanguageCodeFactory('tr', 'tur', 'languageCode@turkish'),
            new LanguageCodeFactory('ts', 'tso', 'languageCode@tsonga'),
            new LanguageCodeFactory('tt', 'tat', 'languageCode@tatar'),
            new LanguageCodeFactory('tw', 'twi', 'languageCode@twi'),
            new LanguageCodeFactory('ty', 'tah', 'languageCode@tahitian'),
            new LanguageCodeFactory('ug', 'uig', 'languageCode@uighurUyghur'),
            new LanguageCodeFactory('uk', 'ukr', 'languageCode@ukrainian'),
            new LanguageCodeFactory('ur', 'urd', 'languageCode@urdu'),
            new LanguageCodeFactory('uz', 'uzb', 'languageCode@uzbek'),
            new LanguageCodeFactory('ve', 'ven', 'languageCode@venda'),
            new LanguageCodeFactory('vi', 'vie', 'languageCode@vietnamese'),
            new LanguageCodeFactory('vo', 'vol', 'languageCode@volapük'),
            new LanguageCodeFactory('wa', 'wln', 'languageCode@walloon'),
            new LanguageCodeFactory('cy', 'wel', 'languageCode@welsh'),
            new LanguageCodeFactory('wo', 'wol', 'languageCode@wolof'),
            new LanguageCodeFactory('fy', 'fry', 'languageCode@westernFrisian'),
            new LanguageCodeFactory('xh', 'xho', 'languageCode@xhosa'),
            new LanguageCodeFactory('yi', 'yid', 'languageCode@yiddish'),
            new LanguageCodeFactory('yo', 'yor', 'languageCode@yoruba'),
            new LanguageCodeFactory('za', 'zha', 'languageCode@zhuangChuang'),
        ]);
    }

    public function load(ObjectManager $manager): void
    {
        foreach ($this->getEntities() as $entity) {
            $manager->persist($entity);
        }

        $manager->flush();
    }

    /**
     * @inheritDoc
     */
    public function getDependencies(): array
    {
        return [
            TranslationDataFixture::class
        ];
    }
}