<?php

namespace App\Infrastructure\Dto;

use App\Infrastructure\Dto\Interfaces\DataTransferCallSetterConstraintHandlerInterface;

abstract class AbstractDataTransferCallSetterConstraintHandler extends AbstractDataTransferConstraintHandler implements DataTransferCallSetterConstraintHandlerInterface
{
}