routing:
  # Basic routing settings
  _settings:
    # Path where all php files with routes will be located
    pathWithRoutes: routes/

    # Software namespace
    softwareNamespace: App\Software\

    # Suffix for files that will contain routes
    routesFileSuffix: ''

  defaultHeaders:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: "*"
    Origin: "api.%env(app.host)%"

  # Created routes
  _routes: {}