services:
  api-response:
    class: App\Services\ResponseApiCollectorService
  password-hashing:
    class: App\Services\PasswordHashingService
  activation-token:
    class: App\Services\Tokens\ActivationTokenService
  session-token:
    class: App\Services\Tokens\SessionTokenService
    construct:
      time: '@provider=time'