view:
  # Path to all templates
  pathWithTemplates: 'resources/templates/'

  # Whether to use the template cache
  useCache: false

  # Which template engine to use to load the template
  engine: Codememory\Components\View\Engines\TwigEngine

  # Expanding twig
  twigExpander: Kernel\Twig\TwigExpander