imports:
  - {resource: 'services/*.yaml'}

parameters:
    jwt.secrets: 'config/secrets/'
    jwt.access_public_key: '%env(JWT_ACCESS_PUBLIC_KEY)%'
    jwt.access_private_key: '%env(JWT_ACCESS_PRIVATE_KEY)%'
    jwt.access_ttl: '%env(JWT_ACCESS_TTL)%'
    jwt.refresh_public_key: '%env(JWT_REFRESH_PUBLIC_KEY)%'
    jwt.refresh_private_key: '%env(JWT_REFRESH_PRIVATE_KEY)%'
    jwt.refresh_ttl: '%env(JWT_REFRESH_TTL)%'

    ws.count_process: '%env(int:WS_PROCESS_COUNT)%'
    ws.host: '%env(WS_HOST)%'
    ws.port: '%env(WS_PORT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        autowire: true
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Enum/'
            - '../src/Service/'
            - '../src/Rest/'
            - '../src/DataFixtures/{Factory,Interfaces,AbstractDataFixture.php}'
            - '../src/Infrastructure/'

    # Packages
    Predis\Client: '@snc_redis.default'
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    Aws\S3\S3Client:
        factory: [Aws\S3\S3Client, factory]
        arguments:
            -
                credentials: {key: '%env(AWS_S3_KEY)%', secret: '%env(AWS_S3_SECRET)%'}
                region: '%env(AWS_S3_REGION)%'
                version: '%env(AWS_S3_VERSION)%'
                endpoint: 's3:9000'
                use_path_style_endpoint: true
                disable_host_prefix_injection: true
    # Rest
    App\Rest\Http\Request:
      public: true

    App\EventListener\KernelException\ApiExceptionListener:
      tags:
        - {name: kernel.event_listener, event: kernel.exception}

    App\Rest\Response\:
      resource: '../src/Rest/Response/*.php'
      exclude:
        - '../src/Rest/Response/Interfaces'

    App\Rest\S3\:
      resource: '../src/Rest/S3/'
      public: true
      exclude:
        - '../src/Rest/S3/{Interfaces}'
        - '../src/Rest/S3/Uploader/{UploadedFile.php,AbstractUploader.php}'

    App\Rest\Jwt\AccessToken:
      public: false

    App\Rest\Jwt\RefreshToken:
      public: false

    # Services
    App\Service\:
      resource: '../src/Service/'
      public: true
      exclude:
        - '../src/Service/DataRepresentation/AbstractDataRepresentation.php'
        - '../src/Service/ObjectComparisonPercentageService.php'
        - '../src/Service/Event/'
        - '../src/Service/Reflection.php'
        - '../src/Service/Parser/'

    App\Service\DataRepresentation\:
      resource: '../src/Service/DataRepresentation/'
      public: true
      exclude:
        - '../src/Service/DataRepresentation/AbstractDataRepresentation.php'

    App\Service\Platform\Google\Client:
      arguments:
        $clientId: '%env(GOOGLE_CLIENT_ID)%'
        $secretKey: '%env(GOOGLE_CLIENT_SECRET)%'
        $redirectUrl: '%env(GOOGLE_CLIENT_REDIRECT_URL)%'
        $scopes:
          - !php/const App\Enum\GoogleScopeEnum::EMAIL
          - !php/const App\Enum\GoogleScopeEnum::PROFILE

    # WebSocket
    App\Service\WebSocket\WorkerConnectionManager:
      public: false

    App\Service\WebSocket\MessageQueueToClient:
      public: false

    App\Service\WebSocket\Worker:
      arguments:
        $host: '%ws.host%'
        $port: '%ws.port%'

    App\Service\WebSocket\Handle\:
      resource: '../src/Service/WebSocket/Handle/*.php'
      public: true

    App\Service\IPGeolocation\IPApi\Client:
      arguments:
        $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
        $url: 'http://ip-api.com/json/'
        $fields:
          - status
          - continent
          - continentCode
          - country
          - countryCode
          - region
          - regionName
          - city
          - district
          - zip
          - lat
          - lon
          - timezone
          - offset
          - currency
          - proxy

    # Parser
    App\Service\Parser\Http\:
      resource: '../src/Service/Parser/Http/*.php'
      public: false

    App\Service\Parser\Zaycev\Parser:
      public: false

    # DTO
    App\Dto\Constraints\:
      resource: '../src/Dto/Constraints/*ConstraintHandler.php'
      public: true

    App\Dto\Transfer\:
      resource: '../src/Dto/Transfer/*Dto.php'
      public: true

    App\Dto\Transformer\:
      resource: '../src/Dto/Transformer/*Transformer.php'
      public: true

    App\Dto\Transfer\WebSocket\:
      resource: '../src/Dto/Transfer/WebSocket/*Dto.php'
      public: true

    App\Dto\Transformer\WebSocket\:
      resource: '../src/Dto/Transformer/WebSocket/*Transformer.php'
      public: true

    # ResponseData
    App\Infrastructure\ResponseData\Constraints\System\:
      resource: '../src/Infrastructure/ResponseData/Constraints/System/*Handler.php'
      public: true

    App\Infrastructure\ResponseData\Constraints\Availability\:
      resource: '../src/Infrastructure/ResponseData/Constraints/Availability/*Handler.php'
      public: true

    App\Infrastructure\ResponseData\Constraints\Value\:
      resource: '../src/Infrastructure/ResponseData/Constraints/Value/*Handler.php'
      public: true

    App\Infrastructure\CronTime\Parser:
      public: false

    App\Infrastructure\Doctrine\Flusher:
      public: false

    App\Infrastructure\File\MimeTypeConverter:
      public: false

    App\Infrastructure\JwtToken\Generator:
      public: false

    App\Infrastructure\Validator\Validator:
      public: false

    App\Infrastructure\Hashing\:
      resource: '../src/Infrastructure/Hashing/*.php'
      public: false

    App\ResponseData\:
      resource: '../src/ResponseData/*ResponseData.php'
      public: true

    # Annotation
    App\Annotation\:
      resource: '../src/Annotation/*Handler.php'
      public: true