parameters:
    jwt.secrets: "config/secrets/"

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        autowire: true
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Enum/'
            - '../src/Service/'
            - '../src/Rest/'

    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    Aws\S3\S3Client:
        factory: [Aws\S3\S3Client, factory]
        arguments:
            -
                credentials: {key: '%env(AWS_S3_KEY)%', secret: '%env(AWS_S3_SECRET)%'}
                region: '%env(AWS_S3_REGION)%'
                version: '%env(AWS_S3_VERSION)%'
                endpoint: "s3:9000"
                use_path_style_endpoint: true
                disable_host_prefix_injection: true

    App\EventListener\ApiExceptionListener:
      tags:
        - { name: kernel.event_listener, event: kernel.exception }

    App\Rest\Http\ResponseSchema:
      public: true
    App\Rest\Http\Response:
      public: true