imports:
    - {resource: 'services/*.yaml'}

parameters:
    jwt.secrets: "config/secrets/"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        autowire: true
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Enum/'
            - '../src/Service/'
            - '../src/Rest/'

    App\Rest\:
        resource: '../src/Rest/*'
        exclude:
            - '../src/Rest/Http/Response.php'
            - '../src/Rest/Abstract*.php'
            - '../src/Rest/*/Abstract*.php'
            - '../src/Rest/*/Abstract*.php'
        public: false

    App\DTO\:
        resource: '../src/DTO/*DTO.php'
        public: false

    App\Service\:
        resource: '../src/Service/'
        exclude:
            - '../src/Service/Abstract*.php'
            - '../src/Service/*/Abstract*.php'
        public: false

    App\Service\Google\GoogleOAuthClient:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            $redirectUrl: '%env(GOOGLE_CLIENT_REDIRECT_URL)%'
            $scopes:
                - !php/const App\Service\Google\GoogleOAuthClient::USERINFO_EMAIL
                - !php/const App\Service\Google\GoogleOAuthClient::USERINFO_PROFILE
                - !php/const App\Service\Google\GoogleOAuthClient::USERINFO_BIRTHDAY

    App\Service\Yandex\YandexOAuthClient:
        arguments:
            $clientId: '%env(YANDEX_CLIENT_ID)%'
            $clientSecret: '%env(YANDEX_CLIENT_SECRET)%'
            $redirectUrl: '%env(YANDEX_CLIENT_REDIRECT_URL)%'
            $avatarSize: '%env(YANDEX_CLIENT_AVATAR_SIZE)%'

    App\Security\:
        resource: '../src/Security/'
        exclude:
            - '../src/Security/Abstract*.php'
            - '../src/Security/*/Abstract*.php'
        public: false